version: "3.9"

services:
  redis:
    image: redis:7.0
    container_name: my-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redis-server" 
    command: ["redis-server", "--requirepass", "redis-server"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
