"""Kiểm tra đồng bộ DB

Revision ID: 23529621eb1b
Revises: 846fad545caf
Create Date: 2025-12-04 21:21:11.713403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23529621eb1b'
down_revision = '846fad545caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('team_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('team_name'), ['team_name'], unique=True)

    # ### end Alembic commands ###
